name: sms_forwarder
description: An SMS forwarding application.

dependencies:
  flutter:
    sdk: flutter

  sms_maintained: ^0.2.5
  http: ^0.12.0
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.1
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shelf_static:  0.2.8

flutter:
  uses-material-design: true
